apiVersion: v1
kind: ReplicationController
metadata:
  name: 'ygawcde-api'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ygawcde-api
        app: ygawcde
    spec:
      nodeSelector:
        ygawc_api: master  # kubectl label nodes 172.18.248.190 ygawc_api=master
      volumes:
        - name: data
          hostPath:
           path: /production/ygawcde_api/data
      containers:
        - name: ygawcde-api
          image: 172.18.248.180:5000/ygawcde_api:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /production/ygawcde_api/data
#          resources:
#            limits:
#              memory: "1024Mi"
          ports:
          - name: ygawcde-api
            containerPort: 23051
            hostPort: 23051
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /ygawcde/api/v1/alive
              port: 23051
            initialDelaySeconds: 60
            timeoutSeconds: 60
          env:
            - name: ETCD_SERVICE_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: etcd-node-info
                  key: endpoints
            - name: ETCD_SERVICE_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: etcd-node-info
                  key: port
